model_name: "facebook/esm2_t6_8M_UR50D"
lora_r: 8
lora_alpha: 16
lora_dropout: 0.1
batch_size: 8
max_length: 512
learning_rate: 0.0005
num_epochs: 3
output_dir: "./output"
seed: 42
label_smoothing: 0.1
use_wandb: true
wandb_entity: "francesco-oteri-perso-sorbonne-universit-"
wandb_project: "protein-sequence-classifier"
wandb_run_name: "esm2-lora-run"
